install.packages('dplyr')
install.packages('Q7.csv')
mean(Q7$Points)
mode(Q7$Points)
sd(Q7$Points)
var(Q7$Points)
range(Q7$Points)
mean(Q7$Score)
mode(Q7$Score)
sd(Q7$Score)
var(Q7$Score)
range(Q7$Score)
mean(Q7$Weigh)
mode(Q7$Weigh)
sd(Q7$Weigh)
var(Q7$Weigh)
range(Q7$Weigh)
hist(Q7$Points)
summary(Q7$Points) ## as mean is less than median it is -ve skewness(lsd)
hist(Q7$Score)
summary(Q7$Score) ## as mean is less than median the it is left skewed distribution(-ve skewness)
hist(Q7$Weigh)
summary(Q7$Weigh) ## as mean is greater than median it ispositive skewness(RSD)
